### ISSUE TITLE
Try to get Molecule running with in-container systemd and multiple roles inside a monorepo

### ISSUE THREAD

**Issue by fschrogl** [fschrogl/infra-automation#36]
I tried to do that as part of #34 but failed due to the following 2 issues:

- systemd wasn't functional in the container images I tried
- testing multiple Ansible roles all contained in one monorepo

In theory, both issues should be solvable but I already spent too much time on #34, so I'm splitting these issues into a new ticket and putting it into the backlog :)

Some documentation on these issues/topics:
- [Molecule: systemd inside a container](https://molecule.readthedocs.io/en/latest/examples.html#systemd-container)
- [Molecule: Monolith repo](https://molecule.readthedocs.io/en/latest/examples.html#monolith-repo)

To run Molecule from a GitHub Action workflow use the following snippet:

```yaml
---
# https://docs.github.com/en/actions
name: Pull Requests
on: [pull_request]

jobs:
  molecule_test:
    name: Running Molecule
    runs-on: ubuntu-latest
    # needs: ansible_lint
    strategy:
      matrix:
        distro:
          - debian11
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          submodules: 'true'
          token: ${{ secrets.PAT_GH_REPOS }}

      - name: Populating secret files
        run: |
          mkdir -p secrets/passwords
          echo "${{ secrets.VAULT_SECRET }}" > secrets/passwords/vault_fsdev.nocommit

      - name: Setup Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Molecule and test dependencies
        run: pip3 install ansible-core molecule[docker] docker

      - name: Execute Molecule
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
        run: |
          cd roles/common
          molecule test
```
